zetalog/sdfirm

arch/arm64/common/head.S, arch/arm64/common/sdfirm.lds.S, arch/arm64/include/asm/page_utils.h, include/asm-generic/sdfirm.lds.h
- Link page data of heap memory in section ".SIMPOINT_MEM_PAGES" of SimPoint
slice into the ".data" section of sdfirm.
- In "__create_page_tables", page table entries are created for these pages by
calling the function "simpoint_heap_map_entry" provided in SimPoint slice.
Additionaly, label "simpoint_heap_map_exit" is inserted and is used as the
branching target at the end of "simpoint_heap_map_entry". A normal return,
i.e. a ret instruction is NOT used here, because we want to reserve all
registers except those used in creating page table entry.
- Macros for creating page entry are moved from head.S to asm/page_utils.h.
=> arm64: Import heap memory pages from SimPoint slice

arch/riscv/configs/duowen_fft_defconfig
Provides an example configuration for RISCV core validating.
=> bench: Add config of FFT for RISCV core validating

kernel/Kconfig, kernel/timer.c
- Add print when calling shutdown.
- Use very small timing period to reduce running time.
=> Fix timer test

arch/riscv/common/clint.c
Use the correct defination CONFIG_RISCV_A.
=> riscv: Fix config bug in clint

tests/bench/Kconfig, tests/bench/tlbtest.c
- Add printing at start and end of test.
- Reduce data buffer size to speed up test.
- Make flush range and flush all optional
=> bench: Refine tlbtest

arch/riscv/include/asm/cpus.h
The struct scratch must be aligned to STACK_ALIGN (16 bytes).
Otherwise it causes the mis-align of SP and introduces a bug in
printf for %llx format under RISCV32.
=> Fix align of struct scratch for RISCV32

tests/bench/hanoitower.c, tests/bench/md5.c
This is useful when we want to check running result automatically.
First get PCs of the pass and fail sub-functions, then check out if they exist in the instruction trace.
=> bench: Add pass and fail sub-functions for tlbtest and md5

arch/riscv/common/Kconfig, arch/riscv/common/clint.c, arch/riscv/configs/benchtimer_rv64_defconfig
This is used for testing interrupt. To enable this feature, turn on the
following configuration:
- CONFIG_CLINT_FORCE_FAST_TIMEOUT
A default config is also provied.
=> clint: Force timer to use a very short timeout

drivers/i2c/Kconfig, drivers/i2c/dw_i2c_master.c
- Install a IRQ handler for certain I2C Master.
- Expects IRQ and check interrupts status in reading of VIP.
=> i2c: Add IRQ test in reading VIP

tests/bench/coremark/Kconfig, tests/bench/coremark/coremark_common.h, tests/bench/coremark/coremark_main.c, tests/bench/coremark/coremark_portme.c, tests/bench/coremark/coremark_portme.h
- CONFIG_COREMARK_RUN_CNT: How many times to run certain count
(defined with CONFIG_COREMARK_ITERATION_CNT) of interations.
- CONFIG_COREMARK_SIMPLE_REPORT: Give a simple report rather than
the original one with details.
- CONFIG_COREMARK_FORCE_VERY_QUICK: Use minimal data size and
iteration count to run quickly.
=> bench: Run and get performance for many times in CoreMark

arch/riscv/mach-duowen/ssi_flash.c, include/target/efi.h
1) Fix bug in converting LBA to byte offset.
2) Change output format to
part-number start-lba end-lba part-uuid part-name (if any)
For Example:
1 2048 2127 part-uuid fsbl.bin
2 4096 32779 part-uuid bbl.bin
3 34816 65502 part-uuid
=> duowen: Fix command flash gpt

arch/riscv/mach-duowen/pcie_duowen.c
In Duowen Soc V3, reset signal which controls PCIE core controllers
is modified to control the custom logic blocks for those controllers
meanwhile
=> Update DUOWEN PCIE configuration for Soc V3 version

include/target/mmc.h, kernel/mmc/card.c, kernel/mtd/mtd_mmcard.c
For mmc_card_read/write_...() functions:
- Use type mmc_lba_t for (block) 'cnt'.
- Make sure that 'lba' stands for LBA number.
=> sd: Fix SD read/write API defination and usage

arch/riscv/mach-duowen/duowen.dts
- UART0 is reserved for OpenSBI and of "disabled" status for Linux
- UART1-3 is "okay" for Linux
- Clock is not given with external clock device with 'clocks', but
given directly with 'clock-frequency`.
- For OpenSBI, BaudRate is configurated in DTS with 'current-speed',
while for Linux, it is configured in DTS but usually given by user
through a 'stty' tool or ioctrl().
=> duowen: Add DTS for all 4 UARTs with fixed clock frequency

arch/riscv/mach-duowen/duowen.dts
Give another clock frequency configuring method for UART1-3.
Refer to existing clock "crcntl0" rather than give a value directly.
=> duowen: Add DTS for UARTs with referenced clock frequency

arch/riscv/mach-duowen/duowen.dts
1. Link speed configuration is available via device tree in 5.12,
add the corresponding to utilize the feature
2. Rename smartcore to smarco
=> Update Duowen PCIe dts for linux-5.12

arch/riscv/mach-duowen/duowen.dts
This patch adds dual socket spi controllers in DTS.
=> duowen: Add dual socket spi controllers in DTS

arch/riscv/mach-dpu/Kconfig, arch/riscv/mach-dpu/mach.c
This patch adds the backdoor for getting small data from rom or getting
huge data from fake pcie memory.
=> dpu: add the backdoor for getting data from rom or fake pcie memory

arch/riscv/include/asm/mach-dpu/pll.h, arch/riscv/mach-dpu/pll.c
This patch adds frequency reduce function test:
1.soft controll:need to config registers of the sft_swallow module to
reduce frequency manually.
2.tsensor auto controll:the tsensor module will reduce freq automatically
when high temprature occurs.
=> dpu: Add frequency reduce funciton test

arch/riscv/include/asm/mach-dpu/pci.h, arch/riscv/mach-dpu/pcie_dpu.c, drivers/pci/pcie_designware.c
This patch adds EP PCIe device support:
1.Use DMA or ATU to communicate with RC device.
2.The EP can access RC's memory through ATU,
but RC can't access EP's memory.
3.There 2 channels for DMA read and 2 channles for DMA write.
4.DMA can be initiated by EP and RC.
5.Support MSI and local interrupt when DMA finished.
6.RC need to malloc/free memory on EP.
=> dpu: Add EP PCIe device support

arch/riscv/include/asm/mach-dpu/pci.h, arch/riscv/mach-dpu/pcie_dpu.c, drivers/pci/pcie_designware.c
This patch adds the APB and DBI access ways for configuring
the PCIe controller.
=> dpu2: EP PCIe device APB and DBI access

arch/riscv/include/asm/mach-dpu/pci.h, arch/riscv/mach-dpu/Kconfig, arch/riscv/mach-dpu/pcie_dpu.c, drivers/pci/pcie_designware.c
This patch adds the PCIe DMA and ATU funciton verification
under vcs and zebu.
1.DMA from/to EP memory to/from RC VIP memory in vcs,
To configure RC memory by ATU at EP side.
2.DMA from/to EP memory to/from RC memory in zebu,
To configure RC memory with info like RC addr allocced,
functionID (ATU rd/write,DMA) at RC side, and
EP can read this info by ATU and then do the
corresponding functionID test.
=> dpu2: PCIe DMA and ATU funciton verification.

arch/riscv/mach-dpu/Kconfig, arch/riscv/mach-dpu/pcie_dpu.c
This patch verifys the DDR through PCIe
DMA huge data when in zebu.
=> dpu2: DDR verification through PCIe DMA huge data.
