- scripts/gem5sim.sh
- Pass parameter for program, if any, with "-O parameter".
- Accept 1..100 as checkpoint number and change it to 00...99 to locate
checkpoint sub-directory under GEM5 output directory.
> gem5sim.sh: Add parameter for programe and fix checkpoint number error

- arch/riscv/Kconfig
- arch/riscv/Makefile
- arch/riscv/common/Kconfig
- arch/riscv/common/plic.c
- arch/riscv/configs/virt_defconfig
- arch/riscv/include/asm/mach-virt/arch.h
- arch/riscv/include/asm/mach-virt/cache.h
- arch/riscv/include/asm/mach-virt/cpus.h
- arch/riscv/include/asm/mach-virt/io.h
- arch/riscv/include/asm/mach-virt/irq.h
- arch/riscv/include/asm/mach-virt/irqc.h
- arch/riscv/include/asm/mach-virt/mem.h
- arch/riscv/include/asm/mach-virt/reg.h
- arch/riscv/include/asm/mach-virt/tsc.h
- arch/riscv/include/asm/mach-virt/uart.h
- arch/riscv/mach-virt/Kconfig
- arch/riscv/mach-virt/Makefile
- arch/riscv/mach-virt/irqc.c
- arch/riscv/mach-virt/mach.c
- drivers/uart/ns16550.c
- kernel/mem.c
Initial version
Signed-off-by: Ge Song<songgebird@gmail.com>
> Support QEMU RISCV virt platform.

- arch/arm64/common/entry.S
- arch/arm64/common/uart_pl01x.c
- arch/arm64/include/asm/uart_pl01x.h
- kernel/console.c
> Correct interrupt handle process in console&uart

- arch/arm64/mach-gem5/timer.c
Signed-of-by: Ge Song <songgebird@gmail.com>
> Adjust to support timer interrupt handle process

- arch/riscv/Kconfig
- arch/riscv/configs/duowen_i2c_defconfig
- arch/riscv/include/asm/mach-duowen/i2c.h
- drivers/Kconfig
- drivers/Makefile
- drivers/i2c/Kconfig
- drivers/i2c/Makefile
- drivers/i2c/dw_i2c_master.c
- include/driver/dw_i2c.h
- include/driver/i2c.h
- kernel/i2c/Kconfig
Fixed some issued and rebased.
> riscv: Start supporting Synopsys DesignWare I2C adapter for Duowen

- arch/riscv/mach-duowen/rv-2tap.cfg
- arch/riscv/mach-duowen/rv.cfg
rv.cfg is for current one tap design, rv-2tap is for 2-tap:2-DM
design.
> Add two openocd cfg scripts

- include/target/coremark.h
- include/target/hanoitower.h
- tests/bench/Kconfig
- tests/bench/Makefile
- tests/bench/coremark_common.h
- tests/bench/coremark_list.c
- tests/bench/coremark_main.c
- tests/bench/coremark_matrix.c
- tests/bench/coremark_portme.c
- tests/bench/coremark_portme.h
- tests/bench/coremark_state.c
- tests/bench/coremark_util.c
- tests/bench/hanoitower.c
Details see commit descriptions.
> bench: Add Hanoitower and CoreMark

- arch/riscv/Kconfig
- arch/riscv/mach-dpu/Kconfig
- arch/riscv/mach-dpu/Makefile
- arch/riscv/mach-dpu/pcie_dpu.c
- arch/riscv/mach-dpu/pcie_dpu.h
- arch/riscv/mach-duowen/Kconfig
- arch/riscv/mach-duowen/Makefile
- arch/riscv/mach-duowen/pcie_duowen.c
- arch/riscv/mach-duowen/pcie_duowen.h
- drivers/pci/Makefile
- drivers/pci/dw_pcie.c
- drivers/pci/pcie_designware.c
- include/driver/pci_glue.h
- include/driver/pci_regs.h
- include/driver/pcie_designware.h
- kernel/pci/Makefile
- kernel/pci/pci.c
Signed-off-by: Ge Song<songgebird@gmail.com>
> Add PCIE subsystem support in Duowen&DPU

- arch/riscv/common/htif.c
The origin sdfirm does not provied HTIF driver for RISCV32. This patch
adds the write (to host) function by use the same implementation for
RISCV64.
> riscv: Fix write function in HTIF driver for RISCV32

- arch/riscv/mach-spike/openocd-spike64.cfg
> Correct the TAP ID for spike

- arch/riscv/common/head.S
- arch/riscv/mach-spike/Kconfig
- arch/riscv/mach-spike/mach.c
- arch/riscv/sbi/Kconfig
- arch/riscv/sbi/sbi_emulate_csr.c
This is an update for https://github.com/zetalog/sdfirm/pull/37
> Fix timer test shutdown and add shutdown for Spike

- arch/riscv/mach-dpu/Makefile
- arch/riscv/mach-dpu/gpt_util.c
- arch/riscv/mach-dpu/gpt_util.h
- arch/riscv/mach-dpu/mach.c
- scripts/mkimg.sh
Add script tool to create a GPT format image.
Get boot file from SSI flash of GPT format for DPU.
> Create flash image of GPT format and boot from it

- arch/riscv/mach-dpu/pcie_dpu.c
- arch/riscv/mach-dpu/pcie_dpu.h
- drivers/pci/pcie_designware.c
> Update DPU pcie driver to adjust the changes in IC design

- arch/riscv/mach-dpu/gpt_util.c
- arch/riscv/mach-dpu/gpt_util.h
- arch/riscv/mach-dpu/mach.c
- scripts/mkimg.sh
- Fix bug in mkimg.sh
- Fix bug in using of gpt_util
- Split copying of GPT data into partition entries
> dpu: Fix bugs and split copying of GPT data

- arch/riscv/mach-dpu/Kconfig
- arch/riscv/mach-dpu/pcie_dpu.c
- arch/riscv/mach-dpu/pcie_dpu.h
- drivers/pci/pcie_designware.c
- include/driver/pcie_designware.h
> dpu: Add some basic simple tests for PCIE RC

- arch/riscv/mach-dpu/Kconfig
- arch/riscv/mach-dpu/pcie_dpu.c
- drivers/pci/pcie_designware.c
- include/driver/pcie_designware.h
> dpu: Support EP mode and implement a simple DMA write test

- tests/bench/coremark/Kconfig
- tests/bench/coremark/coremark_common.h
- tests/bench/coremark/coremark_list.c
- tests/bench/coremark/coremark_main.c
- tests/bench/coremark/coremark_matrix.c
- tests/bench/coremark/coremark_portme.c
- tests/bench/coremark/coremark_portme.h
- tests/bench/coremark/coremark_state.c
- tests/bench/coremark/coremark_util.c
- Start from latest coremark of commit 7685fd3 date Wed May 27
10:02:54 2020 -0700.
- Fix time computing.
- Iteration count is configurable.
> bench: Update coremark

- drivers/i2c/dw_i2c_master.c
- drivers/spd/spd_ee1004.c
- include/target/i2c.h
- kernel/i2c/i2c_cmd_tool.c
> i2c,spd: Fix compiling error

- kernel/uefi/uefi_gpt.c
- Do not use global variable.
- Disable debug printing as default.
> duowen: Refactory GPT extracting functions

- arch/riscv/mach-duowen/Kconfig
- arch/riscv/mach-duowen/pcie_duowen.c
- drivers/pci/pcie_designware.c
> Add a switch to control output of PCIE debug info

- arch/riscv/include/asm/mach-duowen/i2c.h
> duowen: Fix frequency defination of DW I2C

- scripts/mkimg.sh
- Add the 3rd parameter to specify storage capacity.
- Sort partitions by name.
- Do NOT drop sgdisk outputs.
- Print out partition information.
> Fix script mkimg.sh

- kernel/uefi/uefi_gpt.c
- Reduce memory usage and clean up
- Make debug printing configurable and add prefix
> gpt: Reduce memory usage

- arch/riscv/include/asm/mach-duowen/sd.h
- include/target/mmc.h
- include/target/sd_phy.h
- kernel/mmc/card.c
- kernel/mmc/mmc_core.c
- mtd: Set various data for write test
- mmc: Add block write function
- sd: Fix class defination for SD
- sd: Remove align checking for LBA in read
> Support block write for MMC and fix bugs

- arch/riscv/include/asm/mach-duowen/pci.h
- arch/riscv/mach-duowen/mach.c
- arch/riscv/mach-duowen/pcie_duowen.c
- drivers/pci/pcie_designware.c
- include/driver/pcie_designware.h
> Config Duowen PCIE adaptively for different scenarios

- arch/riscv/include/asm/mach-duowen/pci.h
- arch/riscv/mach-duowen/pcie_duowen.c
> Fix to access correct Duowen PCIE registers

- arch/riscv/mach-duowen/pcie_duowen.c
> Record PCIE initialization execution state to sw scsr register

- arch/riscv/mach-duowen/Kconfig
- arch/riscv/mach-duowen/duowen.dts
- include/dt-bindings/clock/sbi-clock-duowen.h
- Add DTS for I2C Master 0-7.
- Make it configurable in Kconfig
> duowen: Add DTS for I2C masters

- arch/riscv/mach-duowen/Kconfig
- arch/riscv/mach-duowen/duowen.dts
- arch/riscv/mach-duowen/gpio.c
Add GPIO pads for UART2/3 and Flash ast SPI0.
> Add GPIO pads for UART and SPI Flash

- arch/riscv/mach-duowen/duowen.dts
Signed-off-by:Song Yaliang <yaliang.song@qq.com>
> duowen:add dmac dts

- arch/riscv/mach-duowen/duowen.dts
Signed-off-by: SongYaliang <yaliang.song@qq.com>
> duowen dma modify block size

- arch/riscv/mach-dpulp/dpulp.cfg
> Add openocd config script for dpulp

- arch/riscv/mach-dpu/pll.c
This patch adds freq show command.
> dpu: Add freq show command.
